### ISSUE TITLE
Options to install released version

### ISSUE THREAD

**Issue by sbuis** [SticsRPacks/SticsRPacks#2]
Hi Rémi,

could it be possible:
- that SticsRpacks install by default the last released version of the SticsOnR, SticsRFiles, CroptimizR packages (using @*release?)?
- to have options to give the release number to install for each package (including a possibility to ask to install the last pushed versions of the packages)?

thanks

**Comment by VEZY** [comment]
Done.
We can give the version of the packages by updating their versions using `SticsRPacks_update()` *e.g.*:

```r
remotes::install_github("SticsRPacks/SticsRPacks")
SticsRPacks::SticsRPacks_update(ref = list(SticsRFiles= "83b9f8b761b68fbb7ab4fb84bdef2b6bebbd555e",
                                           SticsOnR= "07d9a62372e944b5ee8743513abffadced105eab"))
```
