### ISSUE TITLE
use "latest" instead of "last" for most recent version

### ISSUE THREAD

**Issue by eric-casellas** [SticsRPacks/SticsRPacks#4]
use "latest" instead of "last" for most recent version

(last imply that there will be no more in the futur)

for example in : 
* SticsRFiles::get_stics_versions_compat() return value
* SticsOnR readme.md

**Comment by plecharpent** [comment]
Thank you Eric for your useful suggestion.
All are fixed now in SticsRFiles, SticsOnR and SticsRPacks.
Kind regards
